Footer for page once signed in
Tactakon/Deliverable pull request #36
Opened 2023-02-17 16:46 UTC by JBergen-Dev

Simple HTML footer for the page you're redirected to upon successful sign in.

2023-02-17 17:26 UTC, JBergen-Dev commented
![image](https://user-images.githubusercontent.com/60682870/219723085-bfd46775-03b6-49bb-b4ee-17e3d585bb33.png)

2023-02-17 23:18 UTC, kfagnani approved these changes
Looks good! Approved for Merge.

2023-02-18 00:38 UTC, kfagnani requested changes
Before you merge - add the footer to the createPlaylistPage.html and userPlaylistpage.html... After that - good to go!

2023-02-18 03:20 UTC, kfagnani approved these changes

2023-02-18 03:20 UTC, merged